version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - tests

  tests:
    build: .
    container_name: tests_container
    command: python -m unittest discover -s . -p "test_*.py"
    volumes:
      - .:/app
