name: Python Test

on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        run: |
          docker-compose up --abort-on-container-exit

      - name: Arquivo test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test_results_*.txt

      - name: Stop Docker services
        run: docker-compose down
